<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Linearity and normality</title>

<script src="site_libs/header-attrs-2.7/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>




<style type="text/css">
/* for pandoc --citeproc since 2.11 */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Applied Regression in R</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Lectures
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Lecture Notes</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="01_intro.html">Introduction - goals of regression analysis</a>
        </li>
        <li>
          <a href="02_simple_linear_regression.html">Simple linear regression</a>
        </li>
        <li>
          <a href="03_multiple_linear_regression.html">Multiple linear regression</a>
        </li>
        <li class="dropdown-header">Ploting regression models, marginal effects</li>
        <li>
          <a href="05_model_fit.html">Model fit</a>
        </li>
        <li>
          <a href="06_assumptions.html">Assumptions of linear models</a>
        </li>
        <li>
          <a href="06_diagnostics.html">Regression diagnostics</a>
        </li>
        <li>
          <a href="07_linearity_and_normality.html">Linearity and normality</a>
        </li>
        <li>
          <a href="08_heterscedasticity.html">Homoscedasticity</a>
        </li>
        <li class="dropdown-header">Exporting results and multiple models</li>
        <li class="dropdown-header">Prediction and regularization</li>
        <li class="dropdown-header">Missing values imputations</li>
      </ul>
    </li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Lecture Slides</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="01_slides_intro.html">Introduction - goals of regression analysis</a>
        </li>
        <li>
          <a href="02_slides_simple_linear_regression.html">Simple linear regression</a>
        </li>
        <li>
          <a href="03_slides_multiple_linear_regression.html">Multiple linear regression</a>
        </li>
        <li>
          <a href="04_slides_model_visualization.html">Ploting regression models, marginal effects</a>
        </li>
        <li>
          <a href="05_slides_model_fit.html">Model fit</a>
        </li>
        <li>
          <a href="06_slides_model_assumptions.html">Assumptions of linear models and diagnostics</a>
        </li>
        <li>
          <a href="07_slides_nonlinearity.html">Linearity</a>
        </li>
        <li class="dropdown-header">Homoscedasticity</li>
        <li class="dropdown-header">Exporting results and multiple models</li>
        <li class="dropdown-header">Prediction and regularization</li>
        <li class="dropdown-header">Missing values imputations</li>
      </ul>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Practice
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="01_intro_R_excercises.html">Introduction - goals of regression analysis</a>
    </li>
    <li>
      <a href="02_simple_linear_regression_excercises.html">Simple linear regression</a>
    </li>
    <li>
      <a href="03_multiple_linear_regression_excercises.html">Multiple linear regression</a>
    </li>
    <li>
      <a href="035_multiple_linear_regression_excercises_2.html">Interactions</a>
    </li>
    <li>
      <a href="04_model_visualization_exercises.html">Ploting regression models, marginal effects</a>
    </li>
    <li>
      <a href="05_model_fit_exercises.html">Model fit</a>
    </li>
    <li class="dropdown-header">Assumptions of linear models</li>
    <li class="dropdown-header">Regression diagnostics</li>
    <li class="dropdown-header">Linearity and normality</li>
    <li class="dropdown-header">Homoscedasticity</li>
    <li class="dropdown-header">Exporting results and multiple models</li>
    <li class="dropdown-header">Prediction and regularization</li>
    <li class="dropdown-header">Missing values imputations</li>
  </ul>
</li>
<li>
  <a href="completion_requirements.html">Completion Requirements</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Materials
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="course_data.html">Course data</a>
    </li>
    <li>
      <a href="literature.html">Literature</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://ksoc.ff.cuni.cz/">Department website</a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Linearity and normality</h1>

</div>


<p>In this chapter, we will look into ways of modeling nonlinear relationship, as well solving the problem of nonconstant variance.</p>
<div id="modeling-nonlinearity" class="section level1">
<h1>Modeling nonlinearity</h1>
<p>There are many ways one could go around modeling nonlinear relationship through regression models. We will present three basic, which are common and easy to implement: a) categorization b ) polynomial functions and c) splines, also called piecewise polynomials.</p>
<p>For demonstration, we will use data from the eight round of the European Social Survey. More specificaly, data on voter turnouver per age group in the last pairlamentary elections in the Czech republic. Just by ploting the data, we can notice a nonlinear relationship between voter turnout and age:</p>
<pre class="r"><code>ggplot(data = vote, aes(x = agea, y = vote)) +
  geom_point() +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs(x = &quot;Age&quot;, y = &quot;% of respondents who attended the elections&quot;)</code></pre>
<div class="figure">
<img src="07_linearity_and_normality_files/figure-html/age-vs-vote-1.png" alt="Age vs voter turnout" width="672" />
<p class="caption">
Age vs voter turnout
</p>
</div>
<p>We can reach the same conclusion by fitting a linear model and checking the residual plot:</p>
<pre class="r"><code>mod_linear = lm(vote ~ agea, data = vote)

plot(mod_linear, which = 1)</code></pre>
<p><img src="07_linearity_and_normality_files/figure-html/linear-mod-example-1.png" width="672" /></p>
<p>While the sample size is relatively small, the residual plot suggests that simple linear regression may not give us the full picture on the relationship between age and voter turnout.</p>
<div id="categorization" class="section level2">
<h2>Categorization</h2>
<p>THe easiest and by far the most popular way to model nonlinear relationship between variables is to simply categorize the independent variable. The categorization can be done in multiple ways and choice is mostly arbitrary. The <code>ggplot2</code> is particulary helpful, as it offers three categorization function: <code>cut_interval()</code>, <code>cut_number()</code> and <code>cut_width()</code>.</p>
<p>The function <code>cut_interval()</code> discretize a metric variable into <code>n</code> group of equal range. For example, to categorize age into three groups with equal range and plot the model:</p>
<pre class="r"><code>vote$agea_interval = cut_interval(vote$agea, n = 3)

mod_interval = lm(vote ~ agea_interval, data = vote)

plot(ggeffect(mod_interval))</code></pre>
<pre><code>## $agea_interval</code></pre>
<p><img src="07_linearity_and_normality_files/figure-html/cut-interval-example-1.png" width="672" /></p>
<p>As we can see, the age variable was cut into three groups, each with range of 24.65. Alternatively we can use the <code>cut_number()</code> function to categorize age into <code>n</code> groups with (aproximately) the same number of observations:</p>
<pre class="r"><code>vote$agea_number = cut_number(vote$agea, n = 3)

mod_number = lm(vote ~ agea_number, data = vote)

plot(ggeffect(mod_number))</code></pre>
<pre><code>## $agea_number</code></pre>
<p><img src="07_linearity_and_normality_files/figure-html/cut-number-example-1.png" width="672" /></p>
<p>The third option is to discretise the metric variable into categories of equal <code>width</code>. This can be done using the <code>cut_width()</code> function. Notice that it will name the intervals so that they nominally have the same width even if the last interval does not have any observations higher than 90.</p>
<pre class="r"><code>vote$agea_width = cut_width(vote$agea, width  = 30)

mod_width = lm(vote ~ agea_width, data = vote)

plot(ggeffect(mod_width))</code></pre>
<pre><code>## $agea_width</code></pre>
<p><img src="07_linearity_and_normality_files/figure-html/cut-width-example-1.png" width="672" /></p>
<p>The last option is to base the categorization of our data not on the properties of our sample, such as range or quantiles, but determine our the categories according to a theory. For example, in the context of political behavior, people are often categorized into three cohort: a) age 25 and younger b) 26 to 55 years and c) 56 or more.</p>
<pre class="r"><code>vote$agea_theory = case_when(
                             vote$agea &lt;= 25 ~ &quot;25 or less&quot;,
                             vote$agea &lt;= 55 ~ &quot;26 to 55&quot;,
                             vote$agea &gt; 55 ~ &quot;55 or more&quot;)

mod_theory = lm(vote ~ agea_theory, data = vote)

plot(ggeffect(mod_theory))</code></pre>
<pre><code>## $agea_theory</code></pre>
<p><img src="07_linearity_and_normality_files/figure-html/cut-theory-example-1.png" width="672" /></p>
<p>While modeling nonlinear relationships using categorization of metric variables is conveniently easy, it also suffer from a number of problems. <span class="citation">Harrell (2001)</span> provides a list of major problems, among others:</p>
<ul>
<li><p>Estimated values will have reduced precision, and associated tests will have reduced power</p></li>
<li><p>Categorization assumes that the relationship between the predictor and the response is flat within intervals</p></li>
<li><p>Categorization assumes that there is a discontinuity in response as interval boundaries are crossed.</p></li>
<li><p>Cutpoints are arbitrary and manipulatable; cutpoints can be found that can result<br />
in both positive and negative associations</p></li>
</ul>
<p>For these and more reasons described by Harrel, the categorization of interval variables should be in most cases avoided.</p>
</div>
<div id="polynomials" class="section level2">
<h2>Polynomials</h2>
<p>Another option for modeling nonlinearity is to use polynomial functions. Polynomials functions are ones which include an exponent of a variable. An example of a regression model with polynomial function would be</p>
<p><span class="math display">\[
vote = \beta_0 + \beta_1*age + \beta_2*age^2
\]</span></p>
<p>with <span class="math inline">\(age\)</span> being taken to the power of two. This effectively replaces the assumption that the relation between vote and age is a straight line with the assumption that the relationship has a shape of a parabola. We could also use higher order exponents to model increasingly flexible relationships.</p>
<p>There are two types of polynomials - raw polynomials and orthogonal ones. The raw polynomial is simple the variable taken to the power of <em>k</em>. To use second order raw polynomial in a regression model we can write:</p>
<pre class="r"><code>lm(vote ~ poly(agea, 2, raw = TRUE), data = vote)</code></pre>
<p>or alternatively:</p>
<pre class="r"><code>lm(vote ~ agea + I(agea^2), data = vote)</code></pre>
<p>Note that both give the same result.</p>
<p>On the other hand, orthogonal polynomials are computed in such a way that the variable <span class="math inline">\(x^k\)</span> is uncorrelated, i.e. orthogonal, to the original variable <span class="math inline">\(x\)</span>. To compute a second order orthogonal polynomial:</p>
<pre class="r"><code>lm(lm(vote ~ poly(agea, 2), data = vote))</code></pre>
<pre><code>## 
## Call:
## lm(formula = lm(vote ~ poly(agea, 2), data = vote))
## 
## Coefficients:
##    (Intercept)  poly(agea, 2)1  poly(agea, 2)2  
##         0.5769          1.0395         -0.4469</code></pre>
<p>Which of these two types of polynomials should we choose? Both types of polynomials lead to the same model in terms of fit and predictions. However, the estimated regression coefficients are different. The advantage of raw polynomials is that the regression coefficients have the traditional interpretation of <em>change in</em> <span class="math inline">\(y\)</span>, when <span class="math inline">\(x\)</span> is changed by one and <span class="math inline">\(x^k\)</span> is fixed at zero. However, the interpretation of predictors in form of polynomials is difficult no matter what. The major advantage of the orthogonal polynomials is that we can compute the proportion variance explained by each predictor and therefore assess its contribution to the predictive power. If our goal is to interpret the relationship between variables visually through the marginal effects plots, or if we only include the variable as a control, the choice of polynomial type does not matter.</p>
<p>Since the nonlinear relationships are best interpreted visually, we prefer orthogonal polynomials. We can visualize a polynomial regression model using the <code>ggeffects</code> package just like any other multiple linear regression:</p>
<pre class="r"><code>mod_poly = lm(vote ~ poly(agea, 2), data = vote)

plot(ggeffect(mod_poly))</code></pre>
<pre><code>## $agea</code></pre>
<p><img src="07_linearity_and_normality_files/figure-html/poly-example-1.png" width="672" /></p>
<p>While polynomials are often a better option than the categorization approach, they are not without problems. The main problem is that polynomial functions are non local <span class="citation">Harrell (2001)</span>, which means that data in one region can strongly influence predicted values in other regions, especially those with small number of observations. This means that the polynomial regression curves often get “wiggly” and overly curved at the ends. Therefore, polynomial regression tend to provide a good fit only in the regions with most data and are often bad at extrapolation. Polynomials are also bad at modeling relationships that are nonlinear only in certain regions and linear in other. For example, a second order polynomial leads by definition to the shape of a parabola and the regression has to predict a curve along the entire range of data. This means that polynomials are bad at modeling relationship that tend to level of at same point. These problems are especially pronounced with higher degrees polynomials.</p>
<p>In the graph below, we can see, how polynomials can be particularly bad at modeling relationships, that are nonlinear in some regions and linear in others. The blue line is for second order polynomial, the blue one for third order one.</p>
<div class="figure">
<img src="07_linearity_and_normality_files/figure-html/poly-wiggle-1.png" alt="Problem with fitting polynomials to asymptotic data" width="672" />
<p class="caption">
Problem with fitting polynomials to asymptotic data
</p>
</div>
</div>
<div id="splines" class="section level2">
<h2>Splines</h2>
<p>Last of the popular options for modeling nonlinearity are splines, also known as piecewise regression. The idea behind regression splines is fairly straightforward. Instead of trying to fit a single curve through the entire range of data, we can divide the data into smaller bins and fit separate regression lines through each of them.</p>
<pre class="r"><code>ggplot(aes(x = agea, y = vote), data = vote) +
  geom_point() +
  geom_smooth(method = &quot;lm&quot;, se = F, formula = y ~ lspline(x, c(25,50,75))) +
  geom_vline(xintercept = 25, linetype = &quot;dashed&quot;) +
  geom_vline(xintercept = 50, linetype = &quot;dashed&quot;) +
  geom_vline(xintercept = 75, linetype = &quot;dashed&quot;)</code></pre>
<div class="figure">
<img src="07_linearity_and_normality_files/figure-html/splines-example-1.png" alt="Example of spline function, dividing data into 4 bins" width="672" />
<p class="caption">
Example of spline function, dividing data into 4 bins
</p>
</div>
<p>All splines are defined by the number of knots, i.e the number of dividing lines. In the graph above, we see a visualization of regression model with a linear spline and three knots, which divide the range of data into four bins. Formally:</p>
<p><span class="math display">\[
vote = \beta_0 + \beta_1*age_{&lt;25} + \beta_2*age_{25-50} + \beta_3*age_{50-75} + \beta_3*age_{&gt;75}
\]</span></p>
<p>For details on how the spline terms are computed, see <span class="citation">Harrell (2001, p. 22)</span></p>
<div id="linear-splines" class="section level3">
<h3>Linear splines</h3>
<p>The most basic type of splines are the linear splines. These splines fit a straight line through the individual bins. In R, we can use use <code>lspline()</code> function from the <code>lspline</code> package to fit linear splines, with the argument <code>knots</code> specifying the positions of knots/dividing lines. For example:</p>
<pre class="r"><code>mod_ls = lm(vote ~ lspline(agea, knots = c(25,50,75)), data = vote )</code></pre>
<p>Linear splines coefficients are interpreted in the same way as any other coefficients, for example looking at the summary of our model:</p>
<pre class="r"><code>options(show.signif.stars=FALSE)
summary(mod_ls)</code></pre>
<pre><code>## 
## Call:
## lm(formula = vote ~ lspline(agea, knots = c(25, 50, 75)), data = vote)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.282133 -0.067824  0.009675  0.059665  0.298871 
## 
## Coefficients:
##                                         Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)                           -0.6688769  0.2421651  -2.762  0.00749
## lspline(agea, knots = c(25, 50, 75))1  0.0439296  0.0104282   4.213 8.06e-05
## lspline(agea, knots = c(25, 50, 75))2  0.0070266  0.0022336   3.146  0.00251
## lspline(agea, knots = c(25, 50, 75))3  0.0042653  0.0021355   1.997  0.05005
## lspline(agea, knots = c(25, 50, 75))4 -0.0009575  0.0053066  -0.180  0.85738
## 
## Residual standard error: 0.1151 on 64 degrees of freedom
## Multiple R-squared:  0.6191, Adjusted R-squared:  0.5953 
## F-statistic: 26.01 on 4 and 64 DF,  p-value: 8.014e-13</code></pre>
<p>The first of the regression coefficients after the intercept, called <code>lspline(agea, knots = c(25, 50, 75))1</code> tells us the slope of the regression line in the first bin, i.e. for the age of 25 or lower. In other words, for people who are 25 years old or younger, we we would expect on average for people one year older to have 0.044 points higher probability of attending elections. Analogously, the next regression terms refers to the slope in the second bin, i.e. between 25 and 50 year. This coefficient is approximately 0.007 percentage points, showing that the difference in voter turnout based on age are much bigger for the voters below 25 years, than for the middle aged group of people between 25 and 50 years.</p>
<p>As always, we visualize the model using a marginal effects plot. However, the <code>ggeffect</code> package has some trouble correctly picking values of the independent variable to evaluate the model at, so we recommend specifying that all values of the independent variable should be evaluated using <em>[all]</em> as follows:</p>
<pre class="r"><code>plot(ggeffect(mod_ls, terms = &quot;agea [all]&quot;))</code></pre>
<p><img src="07_linearity_and_normality_files/figure-html/ls-marginal-plot-1.png" width="672" /></p>
<p>In the example above, each of the regression coefficients represents the slope of regression line in a given bin.</p>
<p>There is however another way how linear splines can be specified. Instead of the slope itself, the regression coefficients may represent the difference between slopes of two neighboring bins. This can be done by setting argument <code>marginal</code> to <code>TRUE</code>:</p>
<pre class="r"><code>mod_ls_marg = lm(vote ~ lspline(agea, knots = c(25,50,75), marginal = TRUE), data = vote )

summary(mod_ls_marg)</code></pre>
<pre><code>## 
## Call:
## lm(formula = vote ~ lspline(agea, knots = c(25, 50, 75), marginal = TRUE), 
##     data = vote)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.282133 -0.067824  0.009675  0.059665  0.298871 
## 
## Coefficients:
##                                                         Estimate Std. Error
## (Intercept)                                            -0.668877   0.242165
## lspline(agea, knots = c(25, 50, 75), marginal = TRUE)1  0.043930   0.010428
## lspline(agea, knots = c(25, 50, 75), marginal = TRUE)2 -0.036903   0.011643
## lspline(agea, knots = c(25, 50, 75), marginal = TRUE)3 -0.002761   0.003919
## lspline(agea, knots = c(25, 50, 75), marginal = TRUE)4 -0.005223   0.006729
##                                                        t value Pr(&gt;|t|)
## (Intercept)                                             -2.762  0.00749
## lspline(agea, knots = c(25, 50, 75), marginal = TRUE)1   4.213 8.06e-05
## lspline(agea, knots = c(25, 50, 75), marginal = TRUE)2  -3.170  0.00234
## lspline(agea, knots = c(25, 50, 75), marginal = TRUE)3  -0.705  0.48362
## lspline(agea, knots = c(25, 50, 75), marginal = TRUE)4  -0.776  0.44050
## 
## Residual standard error: 0.1151 on 64 degrees of freedom
## Multiple R-squared:  0.6191, Adjusted R-squared:  0.5953 
## F-statistic: 26.01 on 4 and 64 DF,  p-value: 8.014e-13</code></pre>
<p>The first spline coefficient is the same as in the previous model (<code>0.043930</code>). On the other hand, all the following coefficients changed. The second coefficient is now <code>-0.036903</code>, which represents the difference in slopes between the first and the second bin. To compute the slope in the second bin, we can simply add the two coefficients together, <code>0.043930 + (-0.036903) = 0.007027</code>. Notice that this is the same number we got in the previous model for the second spline coefficient. Analogously, we could compute the slope for the third bin by adding the the first, second and third spline coefficient, et cetera.</p>
<p>Computing linear splines this way is particularly useful if you want to test a hypothesis that the relationship between depended and independent variables changes across certain thresholds. For example, if your goal is to test whether the differences in voter turnout based on age differ for people born before and after the fall of the Eastern block, the splines coefficient and its p value can provide this information.</p>
</div>
<div id="natural-cubic-splines" class="section level3">
<h3>Natural cubic splines</h3>
<p>While linear splines provide an easily interpretable way to model nonlinear relationship, they suffer from the same problem as the simple categorization, namely that the results are heavily dependent on the position of the knots (i.e. how is the data split into bins) and that the placement of the knots is often largely arbitrary.</p>
<p>This problem can be solved by using an useful generalization of linear splines, called natural cubic splines or restricted cubic splines. Natural cubic splines are similar to polynomial functions in that we are using a polynomial, more specifically cubic, function to model relationships in our data. There are however two distinctions, which make natural cubic splines a better choice:</p>
<ol style="list-style-type: decimal">
<li>Natural cubic splines divide the data into bins just as linear splines. This solves the problem of non locality, i.e. the fit in one region will not be overly dependent on the fit in other regions like we saw with polynomials.</li>
<li>The polynomial function is only used in the “inner” bins. In the “outer” bins (i.e. in the first and the last one), a simple linear function is fitted. This reduces the “wiggliness” of the regression line typical for polynomial functions, improves fit at the ends and usually leads to better extrapolation results.</li>
</ol>
<p>The following graph illustrates how natural cubic splines are fitted. The data in the very first and very last bin will always be fitted using straight line, while in the inside bins curves are used.</p>
<div class="figure">
<img src="07_linearity_and_normality_files/figure-html/ns-example-bins-1.png" alt="Natural splines fit polynomials in the inner bins and lines in the outer ones" width="672" />
<p class="caption">
Natural splines fit polynomials in the inner bins and lines in the outer ones
</p>
</div>
<p>The location of the knots can be specified based on theory, however for the natural cubic splines it is customary to put them on quantiles in such a way that the knots are evenly spaced along the entire range of the data. The location of the knots for natural cubic splines should also be symmetric around the median. The most common locations of the knots, based on their number are <span class="citation">(Harrell, 2001, p. 27)</span>:</p>
<table>
<thead>
<tr class="header">
<th>knots</th>
<th></th>
<th></th>
<th>Quantiles</th>
<th></th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>3</td>
<td></td>
<td>0.1</td>
<td>0.5</td>
<td>0.9</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>4</td>
<td></td>
<td>0.05</td>
<td>0.35</td>
<td>0.65</td>
<td>0.95</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>5</td>
<td></td>
<td>0.05</td>
<td>0.275</td>
<td>0.5</td>
<td>0.725</td>
<td>0.95</td>
<td></td>
</tr>
<tr class="even">
<td>6</td>
<td>0.05</td>
<td>0.23</td>
<td>0.41</td>
<td>0.59</td>
<td>0.77</td>
<td>0.95</td>
<td></td>
</tr>
<tr class="odd">
<td>7</td>
<td>0.025</td>
<td>0.1833</td>
<td>0.33417</td>
<td>0.5</td>
<td>0.6583</td>
<td>0.8167</td>
<td>0.975</td>
</tr>
</tbody>
</table>
<p>For example, if we decide to use three knots (which would divide the data into four bins), we would place the first knot at the 10th quantile, the second at the 50th quantile and the last one at the 90th quantile. More than seven knots are rarely needed (in fact three knots are most often satisfactory), but if more are needed, the logic stays the same.</p>
<p>To fit a natural cubic splines in R, we can use the <code>ns()</code> function from the <code>splines</code> package. The number of knots can be specified in two ways. First, we can select position of the knots manualy through the <code>knots</code> and <code>Boundary.knots</code> arguments. The <code>knots</code> argument is a vector representing the position of the inner knots, while <code>Boundary.knots</code> is a vector representing the position of the "boundary knots, i.e. the very first and the very last one.</p>
<p>To place three knots manually according to Harrel’s recommendation:</p>
<pre class="r"><code>quantile(vote$agea, probs = 0.5) # returns value of 53
quantile(vote$agea, probs = c(0.1, 0.9)) # returns values of 25.8 and 80.2

mod_ns_manual = lm(vote ~ ns(agea, knots = 53, Boundary.knots = c(25.8, 80.2)), data = vote)</code></pre>
<p>The code above a single inner knot at the 50th quantile and two boundary knots, at 10th and 90th quantile. Unfortunately, the <code>ggeffects</code> package does not seem to work nicely with the output of the quantile() function and so it is better to specify the <code>knots</code> and the <code>Boundary.knots</code> arguments manually like in the code above (separately use quantile to retrieve the value you need and hard-code the value in the <em>lm</em> call in the <em>ns</em> function).</p>
<p>Alternative approach is to specify the knots through the degrees of freedom. The <code>df</code> argument places <code>df - 1</code> inner knots, plus two boundary knots at the sides. Therefore, to place three knots in total, we would specify <code>df = 2</code> (a single inner knot + two boundary knots). Again, it is better for <code>ggeffects</code> to compute marginal effects for all values of the independent variable:</p>
<pre class="r"><code>mod_ns_df = lm(vote ~ ns(agea, df = 3), data = vote)

plot(ggeffect(mod_ns_df, terms = &quot;agea [all]&quot;))</code></pre>
<p><img src="07_linearity_and_normality_files/figure-html/ns-example-df-1.png" width="672" /></p>
<p>It is worth mentioning that the <code>splines</code> package places knots by default at slightly different positions than that recommended by <span class="citation">Harrell (2001)</span>. For example, the boundary knots are placed at the maximum and the minimum of the data, when specified by the <code>df</code> argument. However, the differences in the final model are generally speaking minimal. This can be seen in the graph below, where the differences between the models fitted according to the recommendation by Harrel and the default of the splines package are minimal :</p>
<pre class="r"><code>ggplot(aes(x = agea, y = vote), data = vote) +
  geom_point() +
  geom_smooth(method = &quot;lm&quot;, se = F, formula = y ~ ns(x, knots = 53, Boundary.knots = c(25.8, 80.2)), alpha = 0.5) +
  geom_smooth(method = &quot;lm&quot;, se = F, formula = y ~ ns(x, df = 2), color = &quot;red&quot;, alpha = 0.5)</code></pre>
<div class="figure">
<img src="07_linearity_and_normality_files/figure-html/ns-harrel-vs-splines-1.png" alt="Natural cubic splines fitted according to Harrel's adviace (blue) and the default splines package setting (red)" width="672" />
<p class="caption">
Natural cubic splines fitted according to Harrel’s adviace (blue) and the default splines package setting (red)
</p>
</div>
<p>This illustrates the advantage of the natural cubic splines, namely that they are relatively robust to the arbitrary decisions such as the placements of the knots. As long as the number of the knots is identical and they are placed evenly and symmetrically along the range of the data, the results will be mostly the same.</p>
</div>
<div id="selecting-the-position-and-the-number-of-knots" class="section level3">
<h3>Selecting the position and the number of knots</h3>
<p>While splines represent a very flexible option to plotting nonlinear relationship, the researcher must still select the total number of the knots, as well as where to place them, which introduces some subjectivity to the analysis.</p>
<p>Linear splines are very sensitive to both the number of knots and their position. Both should therefore be based on theory and substantive understanding of the domain, as empirically selected placements generally do not reproduce across studies <span class="citation">(Harrell, 2001, p. 19)</span>.</p>
<p>Natural/restricted cubic splines are more robust to the exact positions and so the number of knots becomes the main question. As a rule of thumb, <span class="citation">Harrell (2001, p. 28)</span> recommends three knots for small samples (n &lt; 30), four knots for medium datasets (30 &lt; n &lt; 100) and five knots for large datasets (n &gt; 100). A more empirical way of selection the number of knots is to fit several models, each with different number of knots. Since each knot represent additional regression coefficient, we could simply compare models with different number of knots and select the one which has the best fit, after adjusting for the different number of parameters (using e.g. adjusted R Squared or Akaike’s Information Criterion).</p>
</div>
</div>
<div id="which-approach-we-should-use" class="section level2">
<h2>Which approach we should use?</h2>
<p>We went over three approaches to model nonlinearity: categorization, polynomials and splines. Which one should be used when?</p>
<p>Categorization is the most problematic of the approaches, given its sensitivity to cutpoints placements, often unreasonable assumptions of the flat relationships between the variables inside a bin, loss of precision and statistical power, as well as other problems described by Harrel. On the other hand, the one big strength of categorization is its simplicity, as most people are able to understand simple means. Therefore, categorization should be considered when we present our results to lay audience, unfamiliar with interpretation of quantitative data.</p>
<p>Linear splines can be seen as a more flexible version of the categorization approach. They still suffer from the arbitrariness of the knots/cutpoints placement, but they do not assume the flat relationship inside bins (note that by flat we mean having no slope) and, if the knots are properly placed, do not suffer from the loss of statistical power. At the same time, the regression coefficient are still easily interpreted without the needs for marginal effect plots. Linear splines are therefore ideal when we want to present our model in a table form to professional arguments (which is common at conferences, technical reports and academic papers, especially when the models are simple enough to be meaningfully presented in a tabular form).</p>
<p>Polynomials in theory represent a simple way to model nonlinear relationship without a need of categorization. However, the fact that polynomial functions are non local and by definition have to follow a polynomial function greatly limits their usefulness, as it makes them both unstable (especially at the “ends”) and unable to model certain types of non-linear relationships (such as when the curve is first bent, but levels out to straight line eventually). This is not helped by the fact that the regression coefficient of polynomial functions are hard to interpret substantially (we usually need to rely on plotting the marginal effects for interpretation).</p>
<p>Natural/restricted cubic splines are the most flexible way to model nonlinearity presented here. They are able to represent relationships of most shapes and do not suffer from the loss of statistical power in the same way as categorization. Unlike linear splines, they are also relatively robust to the placement of the knots. Their most significant disadvantage is the inability to interpret regression coefficient in a substantive manner, a shortcoming which they share with simple polynomials. However, unlike simple polynomials, they can model wide range of relationships, including ones which are nonlinear in some regions and linear in others. This is demonstrated in the graph below, which shows the natural splines fit (blue) and the simple polynomial fit (red). Despite both models consuming the same number of degrees of freedom (i.e. they both have the same demands in term of sample size), the natural splines model is significantly less “wiggly” and represents the data better than the simply polynomial.</p>
<pre class="r"><code>ggplot(un, mapping = aes(x = GDPperCapita, y = infantMortality)) +
  geom_point() +
  geom_smooth(method = &quot;lm&quot;, se = F, formula = y ~ ns(x, df = 6)) +
  geom_smooth(method = &quot;lm&quot;, se = F, formula = y ~ poly(x, 5), color = &quot;red&quot;)</code></pre>
<div class="figure">
<img src="07_linearity_and_normality_files/figure-html/ns-vs-poly-example-1.png" alt="Natural cubic splines vs Simple polynomial" width="672" />
<p class="caption">
Natural cubic splines vs Simple polynomial
</p>
</div>
<p>To summarize: Use categorization when presenting your analysis to lay audience. Use linear splines if you present to professionals, but still want interpretable regression coefficients. Use natural/restricted cubic splines if you are analyzing potentially complex relationships and are comfortable with using marginal effect plots. Avoid simple polynomials altogether.</p>
</div>
</div>
<div id="references" class="section level1 unnumbered">
<h1 class="unnumbered">References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" line-spacing="2">
<div id="ref-fox2015" class="csl-entry">
Fox, J. (2015). <em>Applied regression analysis and generalized linear models</em> (Third edition). SAGE Publications, Inc.
</div>
<div id="ref-harrellRegressionModelingStrategies2001" class="csl-entry">
Harrell, F. (2001). <em>Regression Modeling Strategies: With Applications to Linear Models, Logistic Regression, and Survival Analysis</em>. Springer-Verlag. <a href="https://doi.org/10.1007/978-1-4757-3462-1">https://doi.org/10.1007/978-1-4757-3462-1</a>
</div>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
