---
title: "Completion requirements"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

To succesfuly complete this course, students are required to do the following:

1) Pick a dataset featured on the [TidyTuesday project](https://github.com/rfordatascience/tidytuesday) (any year).
2) Formulate a research problem related to the data. This research problem can be either predictive or inferential in nature (e.g. Can we predict the popularity of a song on Spotify based on its characteristics? Does the gender wage gap in the US depend on the propotion of women in the field? Are more expensive video games rated better?).
3) Analyze the data using a linear regression model and write a report on your finding. This report should include clear definition of your research problems, description of your data (including descriptive statistics), description of your regression model (both tables and graphs where appropriate), diagnostics of your regression model and overall conclusion. You can transform and filter data as neccesary, but clearly describe all data transformations.
4) Send the final report to alesvomacka@seznam.cz

The due date for the report is the end of the academic year, i.e. the end of September. If you get stuck don't be afraid to ask for a consultation.