---
title: "Applied Regression in R"
---

The course Applied Regression in R is developed and taught at [*Department of Sociology, Faculty of Arts, Charles University*](https://ksoc.ff.cuni.cz/) in Prague.
On this webpage, the course content is made available to everyone to promote open learning. The *Lecture notes* tab contains summary of each lecture, hopefully in enough detail to serve as stand alone study material. The *Slides* tab typically replicates the structure of notes, but serves as a prop for our actual lectures, hence more pictures and less words. Beyond and above the content in *Lecture notes* and *Slides*, the actual lectures also serve to apply and practise things in R and have discussion about the concepts. The *Exercise* tab offers exercise for training with click-to-show solutions. All data we use throughout the course can be downloaded in *Materials* section, where you can also find the list of recommended literature.
Please, let us know if you spot any errors or other problems.   

### Course Annotation

The course will introduce students to linear regression analysis with emphasis on application in the R software.
The course is designed for social science students, which is reflected in its focus on a conceptual understanding of linear regression and practical applications in the social sciences.
The course contains only a small amount of mathematics, but for those interested we refer also to literature with more technical/mathematical treatment of the topics covered.
After completing the course, students should have a good conceptual understanding of linear regression and the diverse purposes for which it is used (description, sample-to-population inference, causal inference, prediction), should command common terminology, understand assumptions associated with regression modeling, be able to verify them and respond adequately in the event of a failure to meet the assumptions.
Above all, though, they should be able to make well-argued decisions when conducting their own regression analysis, and they should be able to present and interpret the results of their analysis correctly.

<br>

### Lecturers

Jaromír Mazák, PhD. ([Jaromir.Mazak\@ff.cuni.cz](mailto:Jaromir.Mazak@ff.cuni.cz){.email})

Aleš Vomáčka, MSc. ([ales\@vomacka.io](mailto:alesvomacka@seznam.cz){.email})

<br>

### Course Implementation in case of Distance Teaching/Learning

For the summer semester 2022, standard in-person (offline) lectures are scheduled. Only if the situation changes would the following apply:


**Online learning platform**: Zoom (if a switch to online happens, enrolled students will receive the link)

**Requirements to pass the course**: same as under normal conditions, see the *Completion requirements* tab.
