---
title: "Lesson 4: Interactions"
subtitle: "Jaromír Mazák & Aleš Vomáčka"
author: "Dpt. of Sociology, Faculty of Arts, Charles University"
date: "Last updated in March 2022"
output:
  ioslides_presentation:
    widescreen: true
csl: "../apa.csl"
bibliography: references_lecture_03.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(here)

countries <- read.csv(here("data", "countries.csv"))
```

## Goals for today

-   Using and interpreting interactions

## Main effects

-   Two kinds of main effects

    -   bivariate association (simple regression) or
    -   conditional/additional effects (multiple regression)

Main effects in equation: $... + \beta_i*X_i +...$

## Interactions

-   Interactions: the effect of one independent variable on the dependent variable varies across levels of another independent variable. Interaction effects as "it depends" effects.

    -   e.g. interaction between smoking and inhaling asbestos in their effect on lung cancer risk
    -   some sociological examples?

Interactions in equation: $... + \beta_1*X_1 + \beta_2*X_2 + \beta_3*X_1*X_2 + ...$
    
    
## Model with interactions vs. two separate models

For an interaction of continuous variable with a binary variable, we could also run two separate models. So why not?
- one model with interaction term = one fit
- one model with interaction term = statistical significance test of the difference of slopes 


## Interpreting interaction coefficients

This can be tricky, we will go through it in the lab part of this session. Also see [@gelman2020, pp. 134-136] for general comments and [@gelman2020, pp. 185-187] for the effect of centering variables in models with interactions.



## References
